[package]
name = "dashy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
env_logger = "0.9.1"
log = "0.4.17"
postgres = {version = "0.19.4", features = ["with-uuid-1"] }
r2d2_postgres = "0.18.1"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
sqlx = { version = "0.6.2", features = ["postgres", "json", "chrono", "uuid", "time", "runtime-tokio-rustls"] }
#uuid = { version = "1.1.2" , features = ["serde", "v5"]}
